### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by dor2191** [RyDog199/ACNL-NTR-Cheats#12]
Please excuse my bad English. 

I'm using old3DS 11.0.0-33J on emuNAND.
The game is Japanese ROM(ver 1.1), and the plugin is ver 2.3 JAP.

・An error occurs after using "water all flowers". If I save and finish game before the error occurs, game crashes while game is loading the next time.
・"Player 1 max tan" doesn't work. (Other players are not tested)
・"Moon jump" and "speed hack" don't work.

"Player 1 max tan", "moon jump" and "speed hack" work on old plugin ver which shows "ACNL NTR Cheats Ver 2.3 #DEV J " with white letter on the cheat menu.

**Comment by RyDog199** [comment]
It seems that addresses got shifted in this release O_o
That means I have to re find everything.

**Comment by dor2191** [comment]
I tested 2-4 players max tan. They worked fine!

**Comment by RyDog199** [comment]
Check the latest beta, it should be fixed.
If it is, I'll close this problem.

**Comment by dor2191** [comment]
Thank you! But I can't use PC now, so please wait.

**Comment by dor2191** [comment]
I tested the latest beta (Ver 3.0 Alpha).

Water all flowers ･･･ not fixed
Player 1 Max Tan ･･･ not fixed
Moon Jump ･･･ fixed
Speed Hack ･･･ fixed

**Comment by RyDog199** [comment]
fixed

**Comment by dor2191** [comment]
Player 1 max tan is fixed.
Water all flowers doesn't cause error but it doesn't work.

**Comment by RyDog199** [comment]
I couldn't find what caused the crash so I replaced it with the old version from 2.0, therefore it only searches for wilted flowers and replaces them with watered flowers

**Comment by dora2191** [comment]
Oh I'm sorry. Thank you for relpying many times.
